# Used to spin up the API's dependencies when running locally outside of docker
# This file is executed on the post build step of the RepositoryAnalyticsApi projects so no need to manually do it
version: '3'
services:
  redis:
    container_name: repositoryAnalyticsApi_redis
    image: 'redis:5.0.3'
    ports:
      - '6379:6379'

  postgresql:
    container_name: repositoryAnalyticsApi_postgresql
    image: 'postgres:11.2'
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - '5432:5432'