# Used to spin up the API's dependencies when running locally outside of docker
# This file is executed on the post build step of the RepositoryAnalyticsApi projects so no need to manually do it
version: '3'
services:
  elasticsearch:
    container_name: repositoryAnalyticsApi_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.2
    ports:
      - '9200:9200'
  kibana:
    container_name: repositoryAnalyticsApi_kibana
    image: docker.elastic.co/kibana/kibana:6.5.2
    ports:
      - '5601:5601'
  mongodb:
    container_name: repositoryAnalyticsApi_mongodb
    image: 'mongo:3.4.13'
    ports:
      - '27017:27017'