version: '3.4'

services:
  repositoryanalyticsapi:
    image: repositoryanalyticsapi
    build:
      context: .
      dockerfile: RepositoryAnalyticsApi/Dockerfile
    ports: 
      - "32771:80"
    env_file:
      - RepositoryAnalyticsApi\configuration.env

  mongodb:
    image: mongo:3.4.13
    ports:
      - "27017:27017"

  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"

  kibana:
    image: kibana
    ports: 
      - "5601:5601"