version: '3.4'

services:
  repositoryanalyticsapi:
    image: firenza/repository_analytics_api
    environment:
      - GitHubV3ApiUrl=https://api.github.com
      - GitHubGraphQlApiUrl=https://api.github.com/graphql
      - GitHubAccessToken=YOUR_ACCESS_TOKEN
      - RedisConfiguration=redis
      - RedisInstanceName=RepositoryAnalyticsApi
      - DatabaseType=PostgreSql
      - DatabaseConnectionString=Server=postgresql;Database=repository_analytics;User ID=postgres
      - DatabasePassword=mysecretpassword
    ports: 
      - "32771:80"
    depends_on:
      - redis
      # - sqlserver
      - postgresql

  redis:
    image: 'redis:5.0.3'
    ports:
      - '6379:6379'
  
  # sqlserver:
  #   image: 'mcr.microsoft.com/mssql/server:2017-CU12'
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - MSSQL_SA_PASSWORD=<YourStrong!Passw0rd>
  #   ports:
  #     - '1433:1433'

  postgresql:
    image: 'postgres:11.2'
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - '5432:5432'